version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-rc-management
    container_name: deffered-load-rabbitmq
    ports:
      - 8080:15672
      - 5672:5672
  celery_worker:
    build: .
    depends_on:
      - rabbit
    command: celery -A app.tasks worker --loglevel=INFO
    environment:
      - RABBIT_HOST=rabbit
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - rabbit
    command: flask run
    environment:
      - RABBIT_HOST=rabbit
